image: "cirrusci/flutter:2.0.0"

before_script:
    - cd road_monitoring_system/
    - export PATH="$PATH":"$HOME/.pub-cache/bin"

code_quality:
  stage: app_test
  before_script:
    - pub global activate dart_code_metrics
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test:
  stage: app_test
  before_script:
    - pub global activate junitreport
  script:
    - flutter test --machine --coverage | tojunit -o report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/coverage
    reports:
      junit: report.xml
