# To config services postgres

variables:
  POSTGRES_HOST: "db"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"

# Pick PostgreSQL service to be used on all builds.
# Only needed when using a docker container to run your tests in.
services:
  - name: postgres:13
    alias: db

stages:
  - test_server



# This folder is cached between builds
cache:
  paths:
    - ~/.cache/pip/

test_server:
  before_script:
    - python -V  # Print out python version for debugging
    - apt-get update -q
    - cd src/back
    - pip install -r requirements.txt

  stage: test_server
  image: python:latest
  variables:
    DATABASE_URL: "postgresql://postgres@db:5432/$POSTGRES_DB"
  script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test --settings myServer.settings
