stages:
  - app_test
  - app_build

build_debug:
  image: "cirrusci/flutter:2.0.0"
  stage: app_build
  before_script:
    - cd road_monitoring_system/
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
  script:
    - flutter pub get
    - flutter build apk --debug --split-per-abi

  artifacts:
    paths:
      - build/app/outputs/apk/debug/*.apk

build_release:
  image: "cirrusci/flutter:2.0.0"
  stage: app_build
  before_script:
    - cd road_monitoring_system/
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
  script:
    - flutter pub get
    -  flutter build apk --release --build-number=$CI_PIPELINE_ID
  artifacts:
    paths:
      - build/app/outputs/apk/release/*.apk


code_quality:
  image: "cirrusci/flutter:2.0.0"
  stage: app_test
  before_script:
    - cd road_monitoring_system/
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - pub global activate dart_code_metrics
  script:
    - metrics lib -r codeclimate  > code-quality-report.json
  artifacts:
    paths:
      - bin/cache/artifacts/flutter/
    reports:
      codequality: code-quality-report.json
  only: [RoadMonitoringSystemApp]


test:
  image: "cirrusci/flutter:2.0.0"
  stage: app_test
  before_script:
    - cd road_monitoring_system/
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - pub global activate junitreport
  script:
    - flutter test --coverage
#    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
#  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - bin/cache/artifacts/flutter/
    reports:
      junit: coverage.xml
  only: [RoadMonitoringSystemApp]

