# Generated by Django 3.1.5 on 2021-03-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_badpointstemplates_round_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadPointsTemplates',
        ),
    ]
