version: "3.9"
   
services:
  db:
    image: unncgrpteam17/server_db:beta_release
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "18888:22"

  web:
    image: unncgrpteam17/server_web:beta_release
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8866 && python manage.py updatedatabase"
    volumes:
      - .:/code
    ports:
      - "8866:8866"
      - "8888:22"
    depends_on:
      - db
