# Generated by Django 3.1.5 on 2021-02-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20210225_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='badpoints',
            name='valid_status',
            field=models.BooleanField(default=True, verbose_name='If Point is Still Bad'),
        ),
    ]
