# Generated by Django 3.1.5 on 2021-03-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0005_auto_20210304_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
                ('user_overall_mark', models.FloatField(verbose_name='Overall Weighted Mark of User')),
            ],
        ),
    ]
