# Generated by Django 3.1.5 on 2021-02-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20210223_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
                ('start_time', models.DateTimeField(verbose_name='Record Start Time')),
                ('end_time', models.DateTimeField(verbose_name='Record End Time')),
                ('round_log', models.JSONField(verbose_name='Record Log File')),
                ('round_mark', models.FloatField(verbose_name='Mark of Record')),
            ],
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
