# Generated by Django 3.1.5 on 2021-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0004_badpoints_valid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='round_mark',
            field=models.CharField(max_length=1, verbose_name='Mark of Record'),
        ),
    ]
