# Generated by Django 3.1.5 on 2021-02-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_longitude', models.FloatField(verbose_name='Longitude of Point')),
                ('point_latitude', models.FloatField(verbose_name='Latitude of Point')),
                ('point_radius', models.FloatField(verbose_name='Radius of Point')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
                ('start_time', models.DateTimeField(verbose_name='Round Start Time')),
                ('end_time', models.DateTimeField(verbose_name='Round End Time')),
                ('round_log', models.JSONField(verbose_name='Round Log File')),
            ],
        ),
    ]
